import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Crypto-Tracker",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<Head>
				<title>Crypto-Tracker</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/public/top-logo.jpeg' />{" "}
				{/* Adjust the path as needed */}
			</Head>
			<body className={`${inter.className} pic`}>
				{" "}
				{/* Fixed interpolation here */}
				<div>
					<Navbar />
					{children}
				</div>
			</body>
		</html>
	);
}
